/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.7.10-log : Database - vv_mvc
*********************************************************************
*/


/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/vv_mvc /*!40100 DEFAULT CHARACTER SET utf8 */;

USE vv_mvc;

/*Table structure for table authorities */

DROP TABLE IF EXISTS authorities;

CREATE TABLE authorities (
  USERNAME varchar(50) NOT NULL COMMENT '用户名',
  AUTHORITY varchar(50) NOT NULL COMMENT '认证',
  PRIMARY KEY (USERNAME,AUTHORITY),
  UNIQUE KEY UNIQUE_USERNAME_AUTHORTY (USERNAME,AUTHORITY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='认证';

/*Table structure for table users */

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  USERNAME varbinary(50) NOT NULL COMMENT '用户名',
  PASSWORD varbinary(50) NOT NULL COMMENT '密码',
  ENABLED decimal(1,0) NOT NULL COMMENT '是否启用',
  PRIMARY KEY (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户';

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
